spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:15432}/task-management-system
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        generate_statistics: false
        use_sql_comments: false
        format_sql: true

logging:
  level:
    root: info

springdoc:
  swagger-ui:
#    display-request-duration: true
#    disable-swagger-default-url: false
    path: /api-doc.html
#    url: /api-doc.html
#  api-docs:
#    version: OPENAPI_3_1
